{{- if .Values.externalSecrets.enabled}}
# Tell eso how to reach secrets manager. no creds here: 
# eso uses its own pod identity role
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  labels:
    {{- include "fxwatch.labels" . | nindent 4}}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
---
# Keeps the fxwatch-db secret in sync with the rds managed secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fxwatch-db
  labels:
    {{- include "fxwatch.labels" . | nindent 4}}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: {{ .Values.db.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: PGUSER
      remoteRef:
        key: {{ required "db.secretArn is require" .Values.db.secretArn }}
        property: username
    - secretKey: PGPASSWORD
      remoteRef:
        key: {{ .Values.db.secretArn }}
        property: password
{{- end }}